### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by Akuroma** [randy128gamer/BanSystem-PocketMine#1]
Could you add a Report function which is compatible with PurePerms-Ranks so that Supporters and higher can see who sent a report ?:)

**Comment by DoctorClarke** [comment]
A bug has been found, when you kick someone it wont show the reason it says "kicked for ." please fix, thanks.

**Comment by randy128gamer** [comment]
Hi, DoctorClake, I might fix this soon, thanks for letting me know.
